version: 2.1
orbs:
  yarn: itinerisltd/yarn@2.1.1
  heroku: circleci/heroku@1.2.5
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - yarn/test-if-changed:
          git_base_branch: origin/main
          except_branches: 'qa'
          run-command: tryBuild
          paths: ./src
      - heroku/deploy-via-git:
          branch: main
          requires:
            - yarn/test-if-changed
          filters:
            branches:
              only: main
